# Generated by Django 3.1.2 on 2020-10-27 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('instructions', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('DST', 'Dessert'), ('LCH', 'Lunch'), ('DNR', 'Dinner'), ('BKF', 'Breakfast')], default='DNR', max_length=255)),
                ('isPublic', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/')),
                ('amount', models.IntegerField(null=True)),
                ('type', models.CharField(max_length=255)),
                ('prep_time', models.IntegerField(null=True)),
                ('cook_time', models.IntegerField(null=True)),
                ('cook_temp', models.IntegerField(null=True)),
                ('temp', models.CharField(choices=[('F', 'Fahrenheit'), ('C', 'Celcius')], default='F', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
