# Generated by Django 3.1.2 on 2020-10-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('DNR', 'Dinner'), ('DST', 'Dessert'), ('BKF', 'Breakfast'), ('LCH', 'Lunch')], default='DNR', max_length=255),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cook_temp',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='temp',
            field=models.CharField(choices=[('C', 'Celcius'), ('F', 'Fahrenheit')], default='F', max_length=255),
        ),
    ]
