# Generated by Django 3.1.2 on 2020-10-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20201029_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('LCH', 'Lunch'), ('DNR', 'Dinner'), ('BKF', 'Breakfast'), ('DST', 'Dessert')], default='DNR', max_length=255),
        ),
    ]
